### ISSUE TITLE
Disable a tooltip option

### ISSUE THREAD

**Issue by AsafAgranat** [Akryum/vue-tooltip#10]
I'm implementing the tooltip as part of a component. I'm passing the tooltip as a string, like this:
`<ui-button tooltip="Round button"></ui-button>`

Inside the component I check for the presence of the 'tooltip' prop, and pass an object with the string as content:
`return {content: '' + this.tooltip + ''}`

The problem is that if the prop is not present, meaning that `this.tooltip === null`, I can't pass null to `v-tooltip`. The reason is that` v-tooltip` is expecting a `content` property. Otherwise it errors with this:
`TypeError: Cannot read property 'content' of null`

The solution I made so far was to pass the object still, but also add a class to hide the tooltip. So if `tooltip` prop is not present, I return this:
`return {content: '' + this.tooltip + '', classes: 'hidden-tooltip'}`
And then I hide the tooltip via CSS.

But this has the big disadvantage that the tooltip is still created in the DOM, only hidden.

How can I `v-if` the tooltip entirely?

**Comment by Akryum** [comment]
To disable the tooltip, just pass a falsy value to `v-tooltip`. For your case, you can just do this:

```javascript
computed: {
  tooltipContent () {
    return this.tooltip && {content: this.tooltip }
  }
}
```

And in your template:

```html
<div v-tooltip="tooltipContent">
```

**Comment by AsafAgranat** [comment]
It doesn't seem to work. 
Basically, when the tooltip prop is empty it gets `undefined`.

So in the browser I get this:
`Uncaught TypeError: Cannot read property 'content' of undefined`

**Comment by Akryum** [comment]
This is a bug! :boom:
