### ISSUE TITLE
Can tooltip be made hoverable?

### ISSUE THREAD

**Issue by gapipro** [Akryum/vue-tooltip#12]
So can I make ti hoverable somehow?

**Comment by Akryum** [comment]
What is the use case to have a tooltip being interactive? It's not made for that.

**Comment by gapipro** [comment]
For example when you got a "more info" link in tooltip.

**Comment by Akryum** [comment]
Well, that not this library is for, maybe dropdowns or [drop.js](http://github.hubspot.com/drop/docs/welcome/) would be more appropriate. By the way, I don't recommend to have interactive elements displayed by hovering, this is bad for usability and touchscreens.

**Comment by Waals** [comment]
Now that we have a `<v-popover>` component, can we reconsider this feature ? On [the demo page](https://akryum.github.io/v-tooltip/#/), you show how to use `<v-popover>` with an interactive component and a 'click' trigger, but no interaction can be made when using the 'hover' trigger. What do you think ?
