### ISSUE TITLE
Webpack Production - gulp-uglify fails 

### ISSUE THREAD

**Issue by lukepolo** [Akryum/vue-tooltip#4]
For some reason the gulp-uglify fails when trying to import this package : 

`SyntaxError: Unexpected token punc «,», expected punc «:»',`

I've dug through the source code and didn't see anything wrong. (could be my webpack config is bad as well)

**Comment by Akryum** [comment]
Well, more details of your configuration would be great! :)

**Comment by lukepolo** [comment]
```
// ensure we are using the version of Vue that supports templates
    resolve: {
      alias: {
        vue: 'vue/dist/vue.js'
      }
    },
    // use buble loader since it is the default in Elixir
    vue: {
      loaders: {
        js: 'buble-loader'
      }
    },
    module: {
      loaders: [
       {
                test: /\.js$/,
                loader: 'buble', 
               exclude: /node_modules/ 
        },
        {
          test: /\.vue$/,
          loader: 'vue-loader'
        },
        {
          test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
          loader: 'file-loader',
          query: {
            limit: 10000,
            name: '../img/[name].[hash:7].[ext]'
          }
        },
        {
          test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
          loader: 'url-loader',
          query: {
            limit: 10000,
            name: '../fonts/[name].[hash:7].[ext]'
          }
        }
      ]
    }
```

Seems to work ok with everything else

**Comment by Akryum** [comment]
Try importing the source index file instead of the dist which is default.

Le jeu. 29 déc. 2016 à 17:18, Luke Policinski <notifications@github.com> a
écrit :

**Comment by lukepolo** [comment]
I did :-( , that was my first go to see if it was just the compiled version , but ends with same results

**Comment by Akryum** [comment]
And did you try babel instead of bublé?

Le jeu. 29 déc. 2016 à 17:26, Luke Policinski <notifications@github.com> a
écrit :

**Comment by lukepolo** [comment]
I have not , will give a go

**Comment by Akryum** [comment]
I think there are property shortlands going to uglify that it doesn't
understand, like in index.js at then end.

Le jeu. 29 déc. 2016 à 17:31, Luke Policinski <notifications@github.com> a
écrit :

**Comment by lukepolo** [comment]
Yah even babel didn't like it

**Comment by Akryum** [comment]
By the way, try commenting the line with exclude node_modules in the js rule.

**Comment by lukepolo** [comment]
A bit of a different error when doing that

 `message: '/home/vagrant/Code/pm/app.js: SyntaxError: Unexpected token: operator (>)',`

But assuming not all things should be ran through the `babel-loader` at that point

**Comment by Akryum** [comment]
Try importing the dist file explicitly

Le jeu. 29 déc. 2016 à 17:39, Luke Policinski <notifications@github.com> a
écrit :

**Comment by lukepolo** [comment]
`
import VTooltip from './../../../node_modules/v-tooltip/dist/v-tooltip'
Vue.use(VTooltip)
`

This appears (not a minify issue) 
`
Can\'t resolve \'Tooltip\' i
`

**Comment by Akryum** [comment]
Try importing tether, tether-drop, tether-tooltip too.

Le jeu. 29 déc. 2016 à 17:56, Luke Policinski <notifications@github.com> a
écrit :

**Comment by Akryum** [comment]
Could you try with the latest version of `v-tooltip` please?

**Comment by kiwina** [comment]
Webpack still trows error with c => whe i import the source

**Comment by Akryum** [comment]
Closing since it seems to work with:

```javascript
import VTooltip from 'v-tooltip'
Vue.use(VTooltip)
```
