### ISSUE TITLE
IE11 polyfill

### ISSUE THREAD

**Issue by Christilut** [Akryum/vue-tooltip#8]
VTooltip doesn't work on IE11 currently. 

`Object doesn't support property or method 'assign'`

So I guess we can solve that ourselves with an object.assign polyfill but it would be nice if this plugin did that out of the box.

**Comment by dweldon** [comment]
For a more general solution, you may want to try [polyfill.io](https://polyfill.io). I just added:

```html
<script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
```

to my `index.html` and that seems to work. Of course, relying on dynamic polyfills from a 3rd party may not be your cup of tea.

**Comment by Christilut** [comment]
Thanks, good tip.
